[package]
name = "ic-cow-state"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
enum_dispatch = "0.3.1"
ic-sys = { path = "../sys" }
ic-utils = { path = "../utils" }
libc = "0.2.91"
lmdb-rkv = { git = "https://github.com/dfinity-lab/lmdb-rs", rev = "e45bfaaa9055178ab55f8f31bfece50ebd94f901" }
nix = "0.20.0"
num-integer = "0.1.43"
parking_lot = "0.11.1"
lazy_static = "1.4.0"

[dev-dependencies]
tempfile = "3.1.0"
rand = "0.7.3"
