[package]
name = "ic-registry-subnet-features"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.4"
ic-protobuf = { path = "../../protobuf" }
serde = { version = "1.0.99", features = [ "derive" ] }
strum = "0.18.0"
strum_macros = "0.18.0"
