[package]
name = "ic-crypto-internal-basic-sig-ecdsa-secp256r1"
version = "0.8.0"
edition = "2018"

[dependencies]
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-types = { path = "../../../../../types/types" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
openssl = "0.10.29"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
simple_asn1 = "0.5.4"

[dev-dependencies]
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
proptest = "0.9.4"
proptest-derive = "0.1.0"
strum = "0.18.0"
