[package]
name = "phantom_newtype"
version = "0.8.0"
edition = "2018"

[dependencies]
candid = "0.6.15"
serde = "1.0.99"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
proptest = "0.9.4"

[dev-dependencies]
serde_json = "1.0.40"
