[package]
name = "ic-certified-vars"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }
ic-types = { path = "../types/types" }
hex = "0.4.2"
serde = "1"
serde_cbor = "0.11.1"
tree-deserializer = { path = "../tree_deserializer" }