[package]
name = "ic-crypto-internal-tls"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-types = { path = "../../../../types/types" }
openssl = "0.10.29"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dev-dependencies]
ic-crypto-test-utils = { path = "../../../test_utils" }