[package]
name = "ic-canister-client"
version = "0.8.0"
edition = "2018"

[dependencies]
backoff = "0.3.0"
ic-crypto-sha = { path = "../crypto/sha" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
# TODO(CRP-909): use public crate (not the internal one) for ecdsa-secp256k1 when available.
ecdsa-secp256k1 = { path = "../crypto/internal/crypto_lib/basic_sig/ecdsa_secp256k1", package = "ic-crypto-internal-basic-sig-ecdsa-secp256k1"}
ic-interfaces = { path = "../interfaces" }
ic-protobuf = { path = "../protobuf" }
ic-types = { path = "../types/types" }
async-trait = "0.1.36"
bytes = "1.0.1"
ed25519-dalek = "1.0.1"
hyper = { version = "0.14.16", features = ["client", "tcp", "http1", "http2"] }
hyper-tls = "0.5.0"
native-tls = { version = "0.2.7", features = ["alpn"] }
phantom_newtype = { path = "../phantom_newtype" }
prost = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
tokio = { version = "1.9.0", features = [ "macros", "time" ] }
tree-deserializer = { path = "../tree_deserializer" }
url = "2.1.1"

[dev-dependencies]
hex = "0.4.2"
ic-test-utilities = { path = "../test_utilities" }
ic-validator = { path = "../validator" }
libsecp256k1 = "0.5.0"
rand_chacha = "0.2.2"
rand_core = "0.5.1"
tokio-test = "0.4.0"
