[package]
name = "ic-registry-transport"
version = "0.1.0"
edition = "2018"

[dependencies]
candid = "0.6.3"
ic-protobuf = { path = "../../protobuf" }
prost = "0.6"
prost-types = "0.6"
bytes = "0.5.4"
serde = { version = "1.0.99", features = ["derive"] }

[build-dependencies]
prost-build = "0.6"
