[package]
name = "ic-crypto-utils-basic-sig"
version = "0.8.0"
edition = "2018"
description = "Conversion utils for keys of basic signatures"

[dependencies]
base64 = "0.11.0"
ic-protobuf = { path = "../../../protobuf" }
ic-base-types = { path = "../../../types/base_types" }
ic-crypto-internal-basic-sig-der-utils = { path = "../../internal/crypto_lib/basic_sig/der_utils" }
ic-crypto-internal-basic-sig-ed25519 = { path = "../../internal/crypto_lib/basic_sig/ed25519" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
simple_asn1 = "0.5.4"
ed25519-dalek = "1.0.1"

[dev-dependencies]
hex = "0.4.2"
