[package]
name = "ic-artifact-pool"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
clap = "2.33.3"
ic-config = { path = "../config" }
ic-consensus = { path = "../consensus" }
ic-consensus-message = { path = "../consensus/message" }
ic-crypto = { path = "../crypto" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-types = { path = "../types/types" }
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
lazy_static = "1.4.0"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.9.0", features = [ "process" ] }
lmdb-rkv = { git = "https://github.com/dfinity-lab/lmdb-rs", rev = "e45bfaaa9055178ab55f8f31bfece50ebd94f901" }
prost = "0.7.0"
rocksdb = { version = "0.15.0", optional = true }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_json = "1.0.40"
serde-bytes-repr = "0.1.5"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
slog-scope = "4.1.2"
tempfile = "3.1.0"

[dev-dependencies]
criterion = "0.3"
ic-test-artifact-pool = { path = "../test_utilities/artifact_pool" }
ic-test-utilities = { path = "../test_utilities" }
slog-term = "2.6.0"
slog-envlogger = "2.2.0"
slog-async = "2.5.0"
tempfile = "3.1.0"
rand = "0.4.6"
lmdb-rkv-sys = { git = "https://github.com/dfinity-lab/lmdb-rs", rev = "e45bfaaa9055178ab55f8f31bfece50ebd94f901" }

[[bench]]
name = "load_blocks"
harness = false

[features]
default = ["rocksdb"]

[[bin]]
name = "ic-consensus-pool-util"
path = "src/bin/consensus_pool_util.rs"
