[package]
name = "ic-validator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
hex = "0.4.2"
ic-interfaces = { path = "../interfaces" }
ic-types = { path = "../types/types" }
ic-crypto = { path = "../crypto" }
ic-crypto-sha256 = { path = "../crypto/sha256" }

[dev-dependencies]
assert_matches = "1.3.0"
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-sha256 = { path = "../crypto/sha256"}
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
