[package]
name = "ic-http-handler"
version = "0.1.0"
edition = "2018"

[dependencies]
ascii = "1.0.0"
askama = "0.10.5"
candid = "0.6.15"
dfn_http = { path = "../rust_canisters/dfn_http" }
futures-util = "0.3.13"
hex = "0.4.2"
http = "0.2.3"
hyper = "0.13.10"
ic-base-thread = { path = "../base/thread" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-validator = { path = "../validator" }
lazy_static = "1.4.0"
maplit = "1.0.2"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.9.0", features = [ "process" ] }
prost = "0.7.0"
rand = "0.8.3"
regex = "1.3.9"
reqwest = { version = "0.10.10", features = [ "blocking" ] }
serde = "1.0.99"
serde_cbor = "0.11.1"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tempfile = "3.1.0"
tokio = { version = "0.2.22", features = [ "full" ] }

[dev-dependencies]
bytes = "0.5.4"
ic-test-utilities = { path = "../test_utilities" }
pretty_assertions = "0.7.1"
proptest = "1.0.0"
