[package]
name = "ic-error-types"
version = "0.8.0"
edition = "2018"

[dependencies]
candid = "0.7.4"
ic-protobuf = { path = "../../protobuf" }
serde = { version = "1.0.99", features = ["derive", "rc"] }
strum = "0.20.0"
strum_macros = "0.20.0"
