[package]
name = "ic-crypto-tls-interfaces"
version = "0.8.0"
edition = "2018"

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
ic-protobuf = { path = "../../protobuf" }
tokio = { version = "0.2", features = ["net", "io-util"] }
tokio-openssl = "0.4.0"

[dev-dependencies]
maplit = "1.0"
