[package]
name = "ic-replicated-state"
version = "0.1.0"
edition = "2018"

[dependencies]
debug_stub_derive = "0.3.0"
ic-base-types = { path = "../types/base_types" }
ic-cow-state = { path = "../cow_state" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-protobuf = { path = "../protobuf" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
ic-wasm-utils = { path = "../wasm_utils" }
lazy_static = "1.4.0"
phantom_newtype = { path = "../phantom_newtype" }
serde = { version = "1.0.99", features = [ "derive", "rc" ] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tempfile = "3.1.0"

[dev-dependencies]
criterion = "0.3"
criterion-time = { path = "../criterion_time" }
ic-test-utilities = { path = "../test_utilities" }
im = { git = "https://github.com/dfinity-lab/im-rs", branch = "fix-remove-index-ordmap", features = [ "serde" ] }
maplit = "1.0.2"

[[bench]]
name = "bench_intmap"
harness = false
