[package]
name = "ic-crypto-internal-basic-sig-iccsa"
version = "0.8.0"
edition = "2018"

[dependencies]
hex = "0.4.2"
base64 = "0.11.0"
ic-certified-vars = { path = "../../../../../certified_vars" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-tree-hash = { path = "../../../../tree_hash" }
ic-crypto-sha = { path = "../../../../sha" }
ic-types = { path = "../../../../../types/types" }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
serde_cbor = "0.11"
simple_asn1 = "0.5.4"

[dev-dependencies]
# TODO (CRP-912) Replace ic-crypto with ic-crypto-utils-threshold-sig
ic-crypto = { path = "../../../../../crypto" }
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
ic-crypto-test-utils = { path = "../../../../test_utils" }
ic-interfaces = { path = "../../../../../interfaces" }
