[package]
name = "ic-registry-common"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-base-thread = { path = "../../base/thread" }
ic-canister-client = { path = "../../canister_client" }
ic-certified-vars = { path = "../../certified_vars" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../../crypto/utils/threshold_sig" }
ic-interfaces = { path = "../../interfaces" }
ic-nns-constants = { path = "../../nns/constants" }
ic-nns-common = { path = "../../nns/common" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../keys" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
bytes = "1.0.1"
chrono = "0.4.19"
futures = "0.3.6"
hyper = "0.13.10"
hyper-tls = "0.4.3"
prost = "0.7.0"
prost-types = "0.7.0"
rand = "0.7.3"
reqwest = "0.10.10"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
tokio = "0.2.22"
tree-deserializer = { path = "../../tree_deserializer" }
lazy_static = "1.4.0"
url = { version = "2.1.1", features = ["serde"] }
tempfile = "3.0"
thiserror = "1.0"

[dev-dependencies]
ic-crypto = { path = "../../crypto" }
leb128 = "0.2.4"

[build-dependencies]
prost-build = "0.7.0"
