[package]
name = "ic-wasm-types"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-crypto-sha256 = { path = "../../crypto/sha256" }
ic-sys = { path = "../../sys" }
ic-utils = { path = "../../utils" }
serde = { version = "1.0.99", features = ["derive"] }
