[package]
name = "ic-protobuf"
version = "0.8.0"
edition = "2018"

[dependencies]
bincode = "1.2.1"
erased-serde = "0.3.11"
prost = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
slog = {version = "2.5", features = ["nested-values"]}
serde_json = "1.0"

[build-dependencies]
prost-build = "0.7.0"
