[package]
name = "ic-context-logger"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
