[package]
name = "ic-registry-provisional-whitelist"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-protobuf = { path = "../../protobuf" }
