[package]
name = "ic-crypto-internal-basic-sig-der-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
hex = "0.4.2"
simple_asn1 = "0.4.1"

[dev-dependencies]
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }

