[package]
name = "ic-crypto-test-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-crypto-internal-csp-test-utils = { path = "../internal/csp_test_utils" }
ic-crypto-tls-interfaces = { path = "../tls_interfaces" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-common = { path = "../../registry/common" }
ic-registry-keys = { path = "../../registry/keys" }
ic-types = { path = "../../types/types" }
openssl = "0.10.29"
phantom_newtype = { path = "../../phantom_newtype" }
rand = "0.7.3"
serde = { version = "1.0.99", features = [ "derive" ] }
strum_macros = "0.18.0"
tokio = { version = "1.9.0", features = ["net"] }
tokio-openssl = "0.6.0"
