[package]
name = "ic-metrics"
version = "0.8.0"
edition = "2018"

[dependencies]
libc = "0.2.91"
prometheus = { version = "0.12.0", features = [ "process" ] }

[dev-dependencies]
ic-logger = { path = "../logger" }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "^0.9", default-features = false }
