[package]
name = "ic-crypto-internal-bls12381-serde-miracl"
version = "0.1.0"
authors = ["Max <max@dfinity.org>"]
edition = "2018"

[dependencies]
miracl_core = { path = "../../../fs_ni_dkg/miracl_core"}
ic-crypto-internal-types = { path = "../../../types" }

[dev-dependencies]
hex = "0.4.2"
