[package]
name = "ic-messaging"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3.6"
actix = "0.10.0"
async-trait = "0.1.31"
crossbeam-channel = "0.5.0"
hyper = { git = "https://github.com/dfinity-lab/hyper", rev = "82481b6e4957ea9d399c325ff49c794261a1aae0", features = ["runtime", "tcp"] }
ic-base-types = { path = "../types/base_types" }
ic-canonical-state = { path = "../canonical_state" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
#needed for ExecSelect; ideally we would like to get rid of this dep
#after some restructuring of scheduler <-> execution environment interface
ic-embedders = { path = "../embedders" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
num-rational = "0.2.2"
prometheus = { version = "0.9.0", features = [ "process" ] }
rand = "0.7.3"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_json = "1.0.40"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
socket2 = { version = "0.3.19", features = ["reuseport"] }
tokio = { version = "0.2.22", features = ["full"] }
url = "2.1.1"

# TODO(EXC-185): Drop this dependency once scheduler is moved to execution crate.
ic-execution-environment = { path = "../execution_environment" }

[dev-dependencies]
assert_matches = "1.3.0"
bytes = "0.5.4"
ic-base-thread = { path = "../base/thread" }
ic-state-manager = { path = "../state_manager" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
mockall = "0.7.2"
nix = "0.20.0"
proptest = "0.9.4"
prost = "0.7.0"
reqwest = "0.10"
tempfile = "3.1.0"
tiny_http = "0.7"
