[package]
name = "ic-crypto-internal-basic-sig-rsa-pkcs1"
version = "0.8.0"
edition = "2018"

[dependencies]
rsa = "0.4.0"
ic-types = { path = "../../../../../types/types" }
ic-crypto-sha256 = { path = "../../../../sha256" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
num-traits = { version= "0.2.9", default-features = false, features = ["libm"] }
serde = { version = "1.0.99", features = [ "derive" ] }
simple_asn1 = "0.5.4"
num-bigint = "0.4.0"

[dev-dependencies]
hex = "0.4.2"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
