[package]
name = "registry-canister"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "registry-canister"
path = "canister/canister.rs"

[dependencies]
candid = "0.7.4"
cycles-minting-canister = {path = "../../nns/cmc"}
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
ic-base-types = { path = "../../types/base_types/" }
ic-certified-map = { git = "git://github.com/dfinity/cdk-rs", rev = "2112e912e156b271389a51777680de542bb43980" }
ic-crypto-node-key-validation = { path = "../../crypto/node_key_validation" }
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-nns-common = { path = "../../nns/common" }
ic-nns-constants = { path = "../../nns/constants" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
leb128 = "0.2.4"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
url = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
assert_matches = "1.3.0"
canister-test = { path = "../../rust_canisters/canister_test" }
ic-canister-client = { path = "../../canister_client" }
ic-crypto = { path = "../../crypto" }
ic-interfaces = { path = "../../interfaces" }
ic-registry-common = { path = "../common" }
ic-test-utilities = { path = "../../test_utilities" }
lazy_static = "1.4.0"
maplit = "1.0"
rand = { version = "0.7.2", features = ["small_rng"]}
rand_core = "0.5"
rand_distr = "0.3.0"

[build-dependencies]
prost-build = "0.9.0"

[dev-dependencies]
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-nns-test-utils = {path="../../nns/test_utils"}
ic-nns-test-utils-macros = {path="../../nns/test_utils_macros"}
