[package]
name = "ic-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
features = "0.10.0"
bitflags = "1.2.1"
tempfile = "3.1.0"
hex = "0.4.2"

[target.'cfg(target_os = "linux")'.dependencies]
cvt = "0.1.1"
libc = "0.2.74"
