[package]
name = "ic-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
features = "0.10.0"
bitflags = "1.2.1"
hex = "0.4.2"
prost = "0.7.0"

[target.'cfg(target_family = "unix")'.dependencies]
rand = "0.8.3"

[target.'cfg(target_os = "linux")'.dependencies]
cvt = "0.1.1"
libc = "0.2.91"

[dev-dependencies]
tempfile = "3.1.0"