[package]
name = "ic-crypto-node-key-validation"
version = "0.8.0"
edition = "2018"

[dependencies]
########################################################
# Because this crate is used in a canister, we can only
# use dependencies that can be compiled to WebAssembly.
########################################################
chrono = "0.4.19"
dfn_core = { path = "../../rust_canisters/dfn_core" }
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-internal-basic-sig-ed25519 = { path = "../internal/crypto_lib/basic_sig/ed25519" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-fs-ni-dkg = { path = "../internal/crypto_lib/fs_ni_dkg" }
ic-crypto-internal-multi-sig-bls12381 = { path = "../internal/crypto_lib/multi_sig/bls12_381" }
ic-crypto-internal-types = { path = "../internal/crypto_lib/types" }
ic-protobuf = { path = "../../protobuf" }
ic-types = { path = "../../types/types" }
x509-parser = { version = "0.9.1" }

[dev-dependencies]
curve25519-dalek = "3.0.2"
ic-crypto = { path = "../../crypto" }
ic-crypto-test-utils = { path = "../test_utils" }
ic-test-utilities = { path = "../../test_utilities" }
openssl = "0.10.29"
