[package]
name = "ic-crypto-internal-threshold-sig-bls12381"
version = "0.8.0"
edition = "2018"

[dependencies]
arrayvec = "0.5.1"
base64 = "0.11.0"
ff = "0.5.0"
group = "0.2.0"
ic-crypto-internal-bls12381-common = { path = "../../bls12_381/common"}
ic-crypto-internal-bls12381-serde-miracl = { path = "../../bls12_381/serde/miracl" }
ic-crypto-internal-fs-ni-dkg = { path = "../../fs_ni_dkg" }
ic-crypto-internal-types = { path = "../../types" }
ic-crypto-sha256 = { path = "../../../../sha256" }
ic-types = { path = "../../../../../types/types" }
lazy_static = "1.4.0"
libsecp256k1 = "0.5.0"
miracl_core = { version = "4.1.0", package = "miracl_core_bls12381" }
pairing = "0.15.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
rand_core = "0.5.1"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
serde_json = "1.0.40"
simple_asn1 = "0.5.4"
strum_macros = "0.18.0"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4.2"
ic-crypto-internal-csp-test-utils = { path = "../../../csp_test_utils" }
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
ic-crypto-test-utils = { path = "../../../../test_utils" }
ic-types-test-utils = { path = "../../../../../types/types_test_utils" }
proptest = "0.9.4"
proptest-derive = "0.1.0"
rand_core = "0.5.1"
