[package]
name = "ic-crypto-internal-bls12381-common"
version = "0.8.0"
edition = "2018"

[dependencies]
hex = "0.4.2"
ic-crypto-internal-bls12381-serde-miracl = {path = "../serde/miracl"}
ic-crypto-internal-types = { path = "../../types" }
ic-crypto-sha = { path = "../../../../sha" }
miracl_core = { version = "4.1.0", package = "miracl_core_bls12381" }
bls12_381 = { version = "0.5.0", default-features = false, features = ["groups", "pairings", "alloc", "experimental"] }
rand = "0.7.3"
rand_chacha = "0.2.2"
rand_core = "0.5.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { version = "0.2" }

[dev-dependencies]
proptest = "0.9.4"
proptest-derive = "0.1.0"
