[package]
name = "ic-consensus"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-config = { path = "../config" }
ic-consensus-message = { path = "./message" }
ic-crypto = { path = "../crypto" }
ic-interfaces = { path = "../interfaces" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-replicated-state = { path = "../replicated_state" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-protobuf = { path = "../protobuf" }
ic-types = { path = "../types/types" }
hex = "0.4.2"
num-integer = "0.1.41"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.9.0", features = [ "process" ] }
rand = "0.7.3"
rand_chacha = "0.2.2"
rayon = "1.5.0"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
strum = "0.18.0"
strum_macros = "0.18.0"

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3"
ic-artifact-pool = { path = "../artifact_pool" }
ic-config = { path = "../config" }
ic-execution-environment = { path = "../execution_environment" }
ic-ingress-manager = { path = "../ingress_manager" }
ic-messaging = { path = "../messaging" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-manager = { path = "../state_manager" }
ic-test-artifact-pool = { path = "../test_utilities/artifact_pool" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-test-utilities = { path = "../test_utilities" }
mockall = "0.7.2"
proptest = "0.9.4"
slog-async = "2.5.0"
slog-envlogger = "2.2.0"
slog-term = "2.6.0"
tempfile = "3.1.0"

[[bench]]
name = "validate_payload"
harness = false

[features]
default = []
malicious_code = []
