[package]
name = "ic-interfaces"
version = "0.8.0"
edition = "2018"

[dependencies]
async-trait = "0.1.36"
derive_more = { git = "https://github.com/dfinity-lab/derive_more", branch = "master" }
ic-base-types = { path = "../types/base_types" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-protobuf = { path = "../protobuf" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-transport = { path = "../registry/transport" }
ic-types = { path = "../types/types" }
ic-wasm-types = { path = "../types/wasm_types" }
phantom_newtype = { path = "../phantom_newtype" }
prost = "0.7.0"
rand = "0.7.3"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
