[package]
name = "ic-system-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-base-types = { path = "../types/base_types" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
serde = { version = "1.0.99", features = ["derive", "rc"] }

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
lazy_static = "1.4.0"
maplit = "1.0.2"
