[package]
name = "ic-crypto-secrets-containers"
version = "0.8.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.99", features = ["derive"] }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
serde_cbor = "0.11.1"
