
[package]
name = "ic-rosetta-api"
version = "0.0.1"
authors = []
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2018"

[dependencies]
actix-web = "3.0.2"
futures = "0.3.8"
hex = "0.4.2"
ic-types = { path = "../types/types" }
ic-interfaces = { path = "../interfaces" }
im = { git = "https://github.com/dfinity-lab/im-rs", branch = "fix-remove-index-ordmap", features = [ "serde" ] }
ic-canister-client = { path = "../canister_client" }
itertools = "0.9.0"
reqwest = { version = "0.10.8", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
dfn_core = {path = "../rust_canisters/dfn_core"}
dfn_candid = {path = "../rust_canisters/dfn_candid"}
candid = "0.6.10"
dfn_macro = {path = "../rust_canisters/dfn_macro"}
on_wire = {path = "../rust_canisters/on_wire"}
lazy_static = "1.4.0"
ledger-canister = {path = "canister"}
rand = "0.7"
structopt = "0.3.20"
async-trait = "0.1.41"

#temporarily copied from dev-dependencies
actix-rt = "*"

[dev-dependencies]
rand_distr = "0.3.0"
thread_local = "1.0.1"
# ic-scenario-tests = { path = "../scenario_tests" }

[[test]]
name = "tests"
path = "test/test_utils.rs"
