
[package]
name = "ic-rosetta-api"
version = "1.3.0"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2018"
default-run = "ic-rosetta-api"

[dependencies]
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.6"
async-trait = "0.1.41"
base64 = "0.13.0"
candid = "0.7.4"
cycles-minting-canister = {path = "../nns/cmc"}
dfn_candid = {path = "../rust_canisters/dfn_candid"}
dfn_core = {path = "../rust_canisters/dfn_core"}
dfn_macro = {path = "../rust_canisters/dfn_macro"}
dfn_protobuf = {path = "../rust_canisters/dfn_protobuf"}
hex = "0.4.2"
ic-canister-client = { path = "../canister_client" }
ic-crypto = { path = "../crypto" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../crypto/internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-sha = {path = "../crypto/sha/"}
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }
ic-interfaces = { path = "../interfaces" }
ic-nns-common = { path = "../nns/common" }
ic-nns-constants = { path = "../nns/constants" }
ic-nns-governance = { path = "../nns/governance" }
ic-types = { path = "../types/types" }
lazy_static = "1.4.0"
ledger-canister = {path = "ledger_canister"}
log = "0.4.14"
log4rs = "1.0.0"
on_wire = {path = "../rust_canisters/on_wire"}
prometheus = "0.12.0"
rand = "0.7"
reqwest = "0.11.1"
rusqlite = "0.25.3"
serde = "1.0"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3.20"
tempfile = "3.1.0"
tokio = { version = "1.9.0", features = ["full"] }
tree-deserializer = { path = "../tree_deserializer" }
url = "2.2.1"

[[bin]]
name = "utils"
path = "src/utils.rs"

[dev-dependencies]
ed25519-dalek = "1.0.1"
ic-nns-governance = { path = "../nns/governance"}
ic-rosetta-test-utils = { path = "test_utils" }
ic-base-types = { path = "../types/base_types" }
ic-types = { path = "../types/types" }
rand_chacha = "0.2.2"
rand_core = "0.5.1"
futures = "0.3.13"

[[test]]
name = "rosetta-api-tests"
path = "test/test_utils.rs"
