This is a standalone server which implements the https://www.rosetta-api.org/[Rosetta API]

When complete this will allow cryptocurrency exchanges with this binary to read and write ICPT transactions using a standard interface.

The Rosetta API uses slightly different terminology to us:
* Accounts are canisters on our system
* Shards are subnets
* Mempools are the ingress queue

== Building and running Docker image
Building Docker image requires GitHub token `repository` permissions in order to download tarball with the sources via GitHub API. The command below assumes that the token is available in `github-token.txt` in the current working directory.

[source,bash]
....
docker build . \
    --build-arg GITHUB_TOKEN=$(cat github-token.txt) \
    --file Dockerfile \
    --tag dfinity/rosetta-node
....

Once the image is built, start Rosetta API server with

[source,bash]
....
docker run \
    --interactive \
    --tty \
    --publish 8080:8080 \
    --rm \
    dfinity/rosetta-node
....

== Things that are not implemented

None

== Things that are implemented

=== Data Endpoints

==== https://www.rosetta-api.org/docs/NetworkApi.html#networklist[/network/list]

[source,json]
....
{
    "network_identifiers": [
        {
            "blockchain": "Internet Computer",
            "network": "mainnet",
            "sub_network_identifier": {
                "network": "subnet:0x52bc44d5378309ee2abf1539bf",
                "metadata": {}
            }
        },
        {
            "blockchain": "Internet Computer",
            "network": "mainnet",
            "sub_network_identifier": {
                "network": "subnet:0x1dcc4de8dec75d7aab85b567b6",
                "metadata": {}
            }
        },
        ...
    ]
}
....
Perhaps network = subnet rather than subnetwork = subnet?

Create a new endpoint https://github.com/dfinity-lab/dfinity/blob/dmd%2frosetta-init/rs/messaging/src/xnet_payload_builder.rs#L249-L253[this].

Fetch that data return it in the above format.

=== https://www.rosetta-api.org/docs/NetworkApi.html#networkoptions[/network/options]

I'd expect this to always respond with:

[source,json]
....
{
    "version": {
        "rosetta_version": "1.2.5",
        "node_version": "1.0.2",
        "middleware_version": "0.2.7",
        "metadata": {}
    },
    "allow": {
        "operation_statuses": [
            {
                "status": "SUCCESS",
                "successful": true
            }
        ],
        "operation_types": [
            "TRANSFER"
        ],
        "errors": [
        // list of all the values in our error enum
        ],
        "historical_balance_lookup": false
    }
}
....

=== https://www.rosetta-api.org/docs/NetworkApi.html#networkstatus[/network/status]

This is largely the same as the '/block' endpoint, except you want to pull the information from the block at the head of the ingress queue.

=== https://www.rosetta-api.org/docs/AccountApi.html#accountbalance[/account/balance]

First you need to float the https://github.com/dfinity-lab/dfinity/blob/dmd%2frosetta-init/rs/system_api/src/lib.rs#L34[FundsBalance] in a canister up to the https://github.com/dfinity-lab/dfinity/blob/dmd%2frosetta-init/rs/http_handler/src/read.rs#L81[read endpoint] adding 'Funds' to the SignedReadRequest data type. The funds must be signed by consensus, you will also need the 'BlockHeight' and the 'BlockHash'. https://github.com/dfinity-lab/dfinity/blob/dmd%2frosetta-init/rs/http_handler/src/read.rs#L215[handle_read_state] may be a good starting point for seeing how to do this.

I'd advise adding the functions to call this endpoint to 'canister_client' as it does a lot of the work for you and it makes it accessible to other users.

=== https://www.rosetta-api.org/docs/BlockApi.html#block[/block]

A good starting point here is https://github.com/dfinity-lab/dfinity/blob/dmd%2frosetta-init/rs/types/src/consensus.rs#L256[this data structure]. It will provide the block identifier, the hash and the parent block identifier and the timestamp.
What it won't do.

The transactions within a single block aren't stored at the moment so you need to create a trace of the payments made in each transaction and put that into the certified state. Your best bet is to generate these traces in the methods that actually make payments because we make payments in a lot of situations.

Dimitris is the best person to talk to about this part of the code base.

=== https://www.rosetta-api.org/docs/BlockApi.html#blocktransaction[/block/transaction]

This is just returning a subset of the data exposed in /block

=== https://www.rosetta-api.org/docs/MempoolApi.html#mempool[/mempool]

The mempool maps to the ingress queue fairly well, basically any 'Received' or 'Processing' ingress message is conceptually in the mempool. This information can by pulled out of this https://github.com/dfinity-lab/dfinity/blob/dmd%2Frosetta-init/rs/http_handler/src/lib.rs#L162[IngressHistoryReader].

This is pretty low priority because things generally leave the mempool on our blockchain pretty quickly.

=== https://www.rosetta-api.org/docs/MempoolApi.html#mempooltransaction[/mempool/transaction]

Since we don't know the value of our transactions until they are part of a block, we should just always return some sensible default, probably an empty set of transactions. This is something the spec is fine with.

=== Construction API

The construction API can be constructed largely from 'canister_client' code.

=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructioncombine[/construction/combine]
=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionderive[/construction/derive]

We require an on chain action to create a canister/account so according to the spec we shouldn't implement this.
Also according to the spec we should implement all of the endpoints, so I don't know, let's see what the

=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionhash[/construction/hash]



=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionmetadata[/construction/metadata]
=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionparse[/construction/parse]
=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionpayloads[/construction/payloads]
=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionpayloads[/construction/preprocess]
=== https://www.rosetta-api.org/docs/ConstructionApi.html#constructionsubmit[/construction/submit]
