[package]
name = "ic-crypto-internal-fs-ni-dkg"
version = "0.8.0"
edition = "2018"

[dependencies]
hex = "0.4.2"
lazy_static = "1.4.0"
miracl_core = { version = "4.1.0", package = "miracl_core_bls12381" }
rand_chacha = "0.2.2"
zeroize = "1.1.1"
ic-crypto-internal-bls12381-common ={path ="../bls12_381/common"}
ic-crypto-internal-bls12381-serde-miracl = { path = "../bls12_381/serde/miracl" }
ic-crypto-internal-types = { path = "../types" }
ic-crypto-sha256 = { path = "../../../sha256" }

[dev-dependencies]
proptest = "0.9.4"
rand = "0.7.3"
