= Non-interactive DKG =

For faster iterations, this repo contains a copy of
  https://github.com/miracl/core[`miracl_core`] as a local crate in
  `miracl_core`-subdirectory.  The current copy was built from https://github.com/miracl/core/commit/fac4187178a8be7c9c9049b2755f694ccf675338[fac4187]
  according to https://github.com/miracl/core/tree/master/rust#using-miracl-core-with-cargo[these instructions],
  running `python3 config64.py` for curve #31 (bls12381)

== How to play ==

https://nixos.org/guides/install-nix.html[Install Nix], then:

  $ nix-shell
  $ ./runme

We always build in release mode, otherwise the binary is unbearably slow.

== Historical note (blynn) ==

A fast edit-compile-run cycle is the next-best thing to something like GHCi, so
I started this repo. I planned to copy the code to the main repo once I got it
working, then delete this repo. For various reasons, this didn't happen, and
now I regret putting "blynn" in the repo name.

I chose https://github.com/miracl/core[MIRACL] because I struggled with the
`pairing` crate's API, and I didn't want to implement a degree-11 isogeny
(among other things) to hash to a point. MIRACL turned out to have other
advantages:

  * Supports many different curves.
  * Supports many languages, including JavaScript; we can port crypto
  to the browser easily.
  * No dependencies. Can stay within one library for hashing, big integers,
  pairings, etc.
  * Built for speed. For example: a specialized routine for computing
  the product of two pairings. Another example: the final exponentiation
  is exposed as an API call.
  * Written by Mike Scott, the S of "BLS curves" such as BLS12-381.
  I first met him when I was a grad student. He was already an
  experienced crypto programmer. He's only gotten better!
