[package]
name = "ic-crypto-internal-logmon"
description = "Logging and monitoring for crypto"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
ic-metrics = { path = "../../../monitoring/metrics" }
prometheus = { version = "0.12.0", features = [ "process" ] }
