[package]
name = "ic-base-thread"
version = "0.8.0"
edition = "2018"

[dependencies]
futures = "0.3.13"
prometheus = { version = "0.12.0", features = [ "process" ] }
tokio = { version = "1.9.0", features = ["full"] }
