[package]
name = "cycles-minting-canister"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Canister for cycles administration"
edition = "2018"

[dependencies]
candid = "0.6.15"
dfn_candid = {path = "../../rust_canisters/dfn_candid"}
dfn_protobuf = {path = "../../rust_canisters/dfn_protobuf"}
dfn_core = {path = "../../rust_canisters/dfn_core"}
ic-base-types = {path="../../types/base_types"}
ic-nns-common = { path = "../../nns/common" }
ic-types = {path = "../../types/types"}
lazy_static = "1.4.0"
ledger-canister = {path = "../../rosetta-api/ledger_canister"}
on_wire = {path = "../../rust_canisters/on_wire"}
rand = "0.7.3"
serde = "1.0"
yansi = "0.5.0"

[[bin]]
name = "cycles-minting-canister"
path = "src/main.rs"
