[package]
name = "ic-test-identity"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-types = { path = "../../types/types" }
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ed25519-dalek = "1.0.1"
lazy_static = "1.4.0"
rand_chacha = "0.2.2"
rand_core = "0.5.1"
